/** Editorial training positions. These are Échgammon exercises, not imported chess puzzles. */
import {createGame} from './game.mjs';
export const BOTS=Object.freeze([
 {id:'leon',name:'Léon',title:'Le premier compagnon',rank:1,label:'Découverte',piece:'P',tone:'sage',style:'Joue simplement et laisse des occasions.',quote:'Chaque partie commence par un premier pas.',error:.72,top:10,search:0,chess:1,race:1},
 {id:'iris',name:'Iris',title:'L’exploratrice',rank:2,label:'Débutant',piece:'N',tone:'rose',style:'Varie ses coups, explore les deux plateaux.',quote:'Et si nous essayions un autre chemin ?',error:.4,top:6,search:0,chess:1,race:1},
 {id:'nora',name:'Nora',title:'La coureuse',rank:3,label:'Intermédiaire',piece:'B',tone:'teal',style:'Privilégie la course et protège ses pions.',quote:'La victoire est parfois sur la piste d’à côté.',error:.16,top:3,search:0,chess:.9,race:1.4},
 {id:'basile',name:'Basile',title:'Le tacticien',rank:4,label:'Confirmé',piece:'R',tone:'copper',style:'Recherche les captures et les échecs.',quote:'Une pièce sans défense est une invitation.',error:.07,top:2,search:1,chess:1.22,race:1},
 {id:'octave',name:'Octave',title:'Le stratège',rank:5,label:'Avancé',piece:'Q',tone:'violet',style:'Combine ses dés et anticipe les ripostes.',quote:'Un bon coup prépare déjà le suivant.',error:0,top:1,search:2,chess:1,race:1.1},
 {id:'astra',name:'Astra',title:'La gardienne du coffret',rank:6,label:'Expert',piece:'K',tone:'gold',style:'Examine davantage de suites et de réponses.',quote:'Deux mondes. Aucune décision au hasard.',error:0,top:1,search:3,chess:1.06,race:1.06}
]);
export const THEMES={fondamentaux:'Fondamentaux',tactique:'Tactique',des:'Maîtrise des dés',course:'Course & sorties'};
const move=(from,to,extra={})=>({type:'chess',from,to,...extra});
const race=(from,to,extra={})=>({type:'race',from,to,...extra});
const e=(id,title,theme,difficulty,objective,pieces,dice,steps,hints,explanation,extra={})=>({id,title,theme,difficulty,objective,pieces,dice,steps,hints,explanation,...extra});
export const EXERCISES=[
 e('premier-pas','Le premier pas','fondamentaux',1,'Avancez le pion e2 de deux cases.',null,[2,5],[move('e2','e4')],['Un pion peut avancer de deux cases depuis sa case de départ.','Les deux cases doivent être libres. Le coût doit être exact.','Sélectionnez le dé 2, puis le pion e2 et la case e4.'],'Le pion a quitté sa case de départ pour e4. Une valeur de 2 paie exactement ce déplacement ; le 5 reste disponible.'),
 e('saut-cavalier','Un saut bien payé','des',1,'Développez le cavalier b1 sur c3 avec les deux dés.',null,[1,2],[move('b1','c3')],['Le cavalier saute par-dessus les pièces.','Son déplacement coûte toujours 3, quelle que soit la forme du L.','Additionnez 1 et 2 pour jouer b1 → c3.'],'Le cavalier coûte 3 : les deux dés ont été consommés ensemble, sans donner un déplacement supplémentaire.'),
 e('tour-capture','Une pièce sans défense','tactique',1,'Capturez le cavalier noir en a4.',{e1:'wK',h8:'bK',a1:'wR',a4:'bN'},[3,1],[move('a1','a4')],['La tour se déplace en ligne droite.','Le cavalier est à trois cases de la tour.','Jouez la tour a1 → a4 avec le dé 3.'],'La capture élimine le cavalier d’échecs. Elle ne l’envoie pas sur la barre de course.'),
 e('diagonale','L’or de la diagonale','tactique',2,'Capturez la dame noire en f4 avec votre fou.',{e1:'wK',h8:'bK',c1:'wB',f4:'bQ'},[3,5],[move('c1','f4')],['Suivez la diagonale qui part de c1.','Le fou traverse d2 et e3 avant d’atteindre f4.','Jouez c1 → f4 avec la valeur 3.'],'Trois cases en diagonale coûtent 3, pas 6. Les cases intermédiaires sont libres.'),
 e('addition-tour','Deux dés, une décision','des',2,'Prenez la dame en a6 : aucun dé ne suffit seul.',{e1:'wK',h8:'bK',a1:'wR',a6:'bQ'},[2,3],[move('a1','a6')],['La distance entre a1 et a6 est de cinq cases.','Les pièces d’échecs acceptent la somme de deux valeurs.','Sélectionnez 2 et 3, puis jouez a1 → a6.'],'2 + 3 = 5. Les deux valeurs ont payé un seul mouvement. Elles ne peuvent pas être rejouées.'),
 e('mat-ivoire','La touche finale','tactique',3,'Matez le roi ébène en une action.',{f6:'wK',g6:'wQ',h8:'bK'},[1,4],[{type:'chess',mate:true}],['Votre roi protège les cases autour de g7.','Une dame proche du roi adverse peut lui retirer toutes ses cases.','La dame g6 → g7 est un mat payé avec 1.'],'Échec et mat : aucune défense légale n’existe sur l’échiquier. La victoire est immédiate, sans attendre la course.'),
 e('ligne-du-roi','Ne quittez pas la ligne','tactique',3,'Éliminez la tour e8 sans exposer votre roi.',{e1:'wK',e2:'wR',e8:'bR',a8:'bK'},[6,1],[move('e2','e8')],['Votre tour protège votre roi contre celle d’e8.','Un déplacement latéral exposerait votre roi : il est interdit.','Restez sur la colonne e : e2 → e8 avec le dé 6.'],'La tour reste sur la ligne de défense et supprime l’attaquant. Légalité du roi et coût du dé sont vérifiés ensemble.'),
 e('petit-roque','Un roi à l’abri','fondamentaux',2,'Effectuez le petit roque des Ivoire.',{e1:'wK',h1:'wR',e8:'bK'},[2,5],[move('e1','g1',{castle:'K'})],['Le roi et la tour n’ont pas encore bougé.','Le trajet est libre et aucune case traversée n’est attaquée.','Sélectionnez le roi e1, puis g1. Le roque coûte 2.'],'Le roi rejoint g1 et la tour f1. Les conditions classiques de sécurité s’ajoutent au paiement exact de 2.',{rights:{wK:true}}),
 e('promotion','Une nouvelle puissance','fondamentaux',2,'Faites promouvoir le pion a7.',{e1:'wK',h8:'bK',a7:'wP'},[1,5],[move('a7','a8',{promotion:'any'})],['Votre pion est à une case de la dernière rangée.','En arrivant, il devient une dame, une tour, un fou ou un cavalier.','Jouez a7 → a8 avec 1 et choisissez la pièce de promotion.'],'Vous choisissez votre promotion. Les quatre choix sont acceptés dans cet exercice ; un pion ne reste jamais pion sur la dernière rangée.'),
 e('fourchette','Le cavalier aux deux menaces','tactique',3,'Jouez la fourchette royale en f6.',{a1:'wK',g8:'bK',h7:'bQ',e4:'wN'},[3,5],[move('e4','f6')],['Le cavalier doit attaquer le roi et la dame à la fois.','Depuis f6, son L atteint g8 et h7.','Jouez e4 → f6 avec le dé 3.'],'Le cavalier attaque simultanément le roi g8 et la dame h7. L’échec interrompt votre tour ; l’adversaire doit d’abord sauver son roi.'),
 e('parade','Le roi avant les dés','des',3,'Sortez de l’échec grâce à une parade royale.',{e1:'wK',e8:'bR',a8:'bK'},[5,6],[{type:'chess',rescue:true}],['Le roi est attaqué sur la colonne e.','Aucune défense ne coûte 5, 6 ou 11, mais des cases sûres existent.','Choisissez une case sûre pour le roi, par exemple d1. La parade consomme tous les dés.'],'Un lancer défavorable n’est pas un mat. La parade royale permet une défense géométriquement légale et consomme les dés restants.'),
 e('double-pas','Exploiter un double','des',2,'Avancez le pion a2 jusqu’en a4, puis le pion b2 jusqu’en b4.',null,[2,2,2,2],[move('a2','a4'),move('b2','b4')],['Un double fournit quatre valeurs distinctes.','Vous pouvez développer deux pions avec deux de ces valeurs.','Jouez a2 → a4, puis b2 → b4. Chaque action coûte un 2.'],'Deux des quatre valeurs ont été dépensées. Dans une partie, vous pourriez encore jouer les deux valeurs restantes.'),
 e('frapper','Frapper au bon moment','course',1,'Frappez le pion isolé sur la pointe 6.',{a1:'wK',h8:'bK'},[3,4],[race(8,5)],['Les Ivoire avancent vers les numéros décroissants.','Une pointe avec un seul adversaire peut être prise.','Déplacez le pion de la pointe 9 vers la pointe 6 avec 3.'],'Le pion adverse est envoyé sur la barre. Il devra rentrer avant que son camp ne joue d’autres pions de course.',{race:{points:{8:1,5:-1}}}),
 e('proteger','Construire un refuge','course',1,'Réunissez vos deux pions sur la pointe 6.',{a1:'wK',h8:'bK'},[3,4],[race(8,5)],['Une pointe avec deux pions alliés est protégée.','Le pion de la pointe 9 est à trois pas de son allié.','Jouez 9 → 6 avec 3 pour réunir les deux pions.'],'Deux pions alliés ferment la pointe aux adversaires. Contrairement à l’ancien prototype, cette protection n’existe que sur les pistes.',{race:{points:{8:1,5:1,18:-15}}}),
 e('retour-barre','Le retour dans la course','course',2,'Faites rentrer votre pion depuis la barre avec 2.',{a1:'wK',h8:'bK'},[2,4],[race('bar',22)],['Les Ivoire rentrent dans le quadrant 19 à 24.','La valeur 2 correspond à la pointe 23 pour les Ivoire.','Cliquez sur Barre ivoire, puis sur la pointe 23.'],'Le pion a quitté la barre. La contrainte de rentrée concerne la course, pas les pièces d’échecs.',{race:{points:{18:-15},bar:{w:1}}}),
 e('derniere-sortie','Le quinzième pion','course',1,'Sortez votre dernier pion et gagnez la course.',{a1:'wK',h8:'bK'},[3,5],[race(2,'off')],['Votre dernier pion se trouve sur la pointe 3.','Les sorties d’Échgammon demandent la valeur exacte.','Sélectionnez la pointe 3 puis Sortie ivoire, avec le dé 3.'],'C’est votre quinzième sortie : la partie est gagnée immédiatement, même si les rois sont encore sur l’échiquier.',{race:{points:{2:1,18:-15}}}),
 e('ordre-des','Le bon ordre change tout','des',3,'Contournez la pointe fermée : jouez 7 → 5, puis 5 → 4.',{a1:'wK',h8:'bK'},[1,2],[race(6,4),race(4,3)],['Le dé 1 vous conduirait d’abord vers une pointe fermée.','Jouez le 2 en premier. Le 1 deviendra alors utilisable.','Pointe 7 → 5 avec 2, puis 5 → 4 avec 1.'],'Le dé 1 ne devait pas être jeté : le premier mouvement l’a débloqué. Le moteur conserve les valeurs temporairement inutilisables.',{race:{points:{6:1,5:-2,18:-13}}}),
 e('deux-sorties','Une victoire en deux temps','course',2,'Sortez vos deux derniers pions avec 1 et 2.',{a1:'wK',h8:'bK'},[1,2],[{type:'race',to:'off'},{type:'race',to:'off'}],['Les deux pions sont dans votre dernier quadrant.','Chaque sortie utilise un dé séparé ; l’ordre est libre.','Sortez le pion de la pointe 1 avec 1 et celui de la pointe 2 avec 2.'],'Les deux ordres fonctionnent. Les deux pions sont sortis avec deux valeurs distinctes : quinze sorties, victoire.',{race:{points:{0:1,1:1,18:-15}}})
];
const card=(title,text,target)=>({title,text,target});
export const LESSONS=[
 {id:'decouvrir',number:1,title:'Deux mondes, une victoire',subtitle:'Prenez vos repères dans le coffret.',minutes:3,exercise:'premier-pas',cards:[card('Bienvenue dans le coffret','L’échiquier central et les deux pistes se jouent avec les mêmes dés. Vous décidez où investir chaque valeur.','#cabinet'),card('Choisir son objectif','Pour gagner : mater le roi adverse OU sortir vos quinze pions de course. Vous n’avez pas besoin d’accomplir les deux.','.players'),card('À vous de jouer','Commençons par un pion d’échecs. Le dé 2 permet d’avancer e2 jusqu’en e4. Cliquez la pièce, puis sa destination.','#sq-e2')]},
 {id:'payer',number:2,title:'Le langage des dés',subtitle:'Valeurs exactes et combinaisons.',minutes:4,exercise:'saut-cavalier',cards:[card('Chaque valeur est une ressource','Un déplacement d’échecs coûte exactement sa distance. Le cavalier est l’exception : il coûte toujours 3.','#dice'),card('Deux valeurs, un mouvement','Un dé peut payer seul ; deux dés disponibles peuvent aussi être additionnés pour une pièce d’échecs.','#dice'),card('Un saut de cavalier','Les dés 1 et 2 paient ensemble le saut b1 → c3. La course, elle, n’autorise pas cette addition.','#sq-b1')]},
 {id:'capturer',number:3,title:'Voir les occasions',subtitle:'Une capture légale, au juste prix.',minutes:3,exercise:'tour-capture',cards:[card('Observez avant de jouer','Sur l’échiquier, les tours se déplacent horizontalement ou verticalement, sans traverser les pièces.','#sq-a1'),card('Une cible isolée','Le cavalier noir a4 est sur la même colonne que votre tour. Trois cases les séparent.','#sq-a4'),card('La capture est définitive','Une pièce d’échecs capturée est retirée du jeu. Prenez-la avec votre tour ; elle n’ira pas sur la barre.','#sq-a1')]},
 {id:'refuges',number:4,title:'Protéger ses pions',subtitle:'Les points fermés de la course.',minutes:3,exercise:'proteger',cards:[card('La piste des Ivoire','Les Ivoire vont de 24 vers 1. Les Ébène parcourent le chemin inverse.','#track-left'),card('Seul, un pion est vulnérable','Un pion isolé peut être frappé et envoyé sur la barre. Deux pions ensemble ferment leur pointe.','#point-5'),card('Bâtissez votre refuge','Réunissez les pions en jouant la pointe 9 vers la pointe 6 avec le dé 3.','#point-8')]},
 {id:'barre',number:5,title:'Revenir dans la partie',subtitle:'Rentrer après avoir été frappé.',minutes:3,exercise:'retour-barre',cards:[card('La barre n’est pas une élimination','Votre pion attend ici. Il devra rentrer avant vos autres mouvements de course.','#bar-w'),card('Trouver la porte d’entrée','Pour les Ivoire : 1 entre sur 24, 2 sur 23, et ainsi de suite. Deux adversaires ferment une entrée.','#point-22'),card('Reprenez la course','Sélectionnez la barre ivoire puis la pointe 23. Le dé 2 sera consommé.','#bar-w')]},
 {id:'sortir',number:6,title:'L’art de finir',subtitle:'Le dernier quadrant et la sortie.',minutes:3,exercise:'derniere-sortie',cards:[card('Tout le monde à la maison','Vous pouvez sortir lorsque tous vos pions restants sont dans les six dernières pointes et aucun sur la barre.','#track-right'),card('Une valeur exacte','Dans cette édition, un pion sur la pointe 3 sort avec 3. Un dé supérieur ne le fait pas sortir.','#dice'),card('La victoire est à un clic','Sélectionnez votre pion de la pointe 3, puis la zone de sortie ivoire.','#off-w')]},
 {id:'anticiper',number:7,title:'Penser dans le bon ordre',subtitle:'Ne gaspillez pas une valeur bloquée.',minutes:4,exercise:'ordre-des',cards:[card('Un blocage peut être temporaire','Le dé 1 ne permet pas d’avancer de 7 à 6 : deux adversaires ferment cette pointe.','#point-5'),card('Essayez l’autre valeur','Le 2 peut faire sauter votre pion de 7 à 5. Le dé 1 reste disponible.','#dice'),card('Réalisez la séquence','Jouez 7 → 5, puis 5 → 4. Vous aurez utilisé les deux valeurs légalement.','#point-6')]},
 {id:'roi',number:8,title:'Le roi avant tout',subtitle:'Comprendre l’échec et la parade.',minutes:4,exercise:'parade',cards:[card('Votre roi est attaqué','La tour e8 attaque le roi sur la colonne e. Il faut répondre sur l’échiquier avant de jouer la course.','#sq-e1'),card('Les dés ne décident pas du mat','Une défense existe, mais aucun paiement ne convient. Échgammon autorise alors une parade royale.','#dice'),card('Choisissez une case sûre','La parade consomme tous les dés restants. Déplacez le roi sur une des cases sûres indiquées.','#sq-e1')]}
];
export const square=s=>s.charCodeAt(0)-97+(Number(s[1])-1)*8;
export function exerciseState(id){
 const ex=EXERCISES.find(e=>e.id===id);if(!ex)throw new Error('Exercice introuvable.');
 const g=createGame();g.phase='play';g.dice=ex.dice.slice();g.used=g.dice.map(()=>false);g.notice=ex.objective;
 if(ex.pieces){g.chess.board.fill(null);g.chess.rights={wK:false,wQ:false,bK:false,bQ:false,...ex.rights};g.chess.ep=null;for(const [s,p] of Object.entries(ex.pieces))g.chess.board[square(s)]=p;}
 if(ex.race){const r=g.race;r.points.fill(0);for(const [s,n] of Object.entries(ex.race.points))r.points[Number(s)]=n;r.bar={w:0,b:0,...ex.race.bar};for(const side of ['w','b'])r.off[side]=15-r.bar[side]-r.points.reduce((n,p)=>n+Math.max(0,p*(side==='w'?1:-1)),0);}
 return g;
}
export function dailyExercise(date=new Date()){
 const day=Math.floor(Date.UTC(date.getFullYear(),date.getMonth(),date.getDate())/86400000);
 return EXERCISES[((day%EXERCISES.length)+EXERCISES.length)%EXERCISES.length];
}
export function botById(id){return BOTS.find(b=>b.id===id)||BOTS[1];}
