import test from 'node:test';
import assert from 'node:assert/strict';
const C = await import('../echgammon/chess.mjs').catch(() => ({}));
const R = await import('../echgammon/race.mjs').catch(() => ({}));
const G = await import('../echgammon/game.mjs').catch(() => ({}));
const A = await import('../echgammon/ai.mjs').catch(() => ({}));
const sq = s => s.charCodeAt(0)-97+(+s[1]-1)*8;
function chess(pieces, rights = {}) {
  const c = C.createChess(); c.board.fill(null); c.rights={wK:false,wQ:false,bK:false,bQ:false,...rights}; c.ep=null;
  for (const [s,p] of Object.entries(pieces)) c.board[sq(s)]=p;
  return c;
}
function perft(c, side, depth) { if(!depth) return 1; return C.legalChess(c,side).reduce((n,m)=>n+perft(C.moveChess(c,m),side==='w'?'b':'w',depth-1),0); }
function playFixture() { const g=G.createGame(); g.phase='play';g.dice=[1,2];g.used=[false,false];return g; }
function bareRace() { return {points:Array(24).fill(0),bar:{w:0,b:0},off:{w:0,b:0}}; }
function seeded(seed) { return ()=>{seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed/4294967296}; }

test('new chess engine exists and sets up 32 pieces',()=>{assert.equal(typeof C.createChess,'function');assert.equal(C.createChess().board.filter(Boolean).length,32)});
test('standard legal geometry: perft 20, 400, 8902 and 197281',()=>{for(const [depth,n] of [[1,20],[2,400],[3,8902],[4,197281]])assert.equal(perft(C.createChess(),'w',depth),n)});
test('a pinned rook cannot expose its own king',()=>{const c=chess({e1:'wK',e2:'wR',e8:'bR',a8:'bK'});assert.ok(!C.legalChess(c,'w').some(m=>m.from===sq('e2')&&m.to===sq('d2')))});
test('castling respects attacked transit squares and lost rights',()=>{let c=chess({e1:'wK',a1:'wR',h1:'wR',e8:'bK'}, {wK:true,wQ:true});assert.equal(C.legalChess(c,'w').filter(m=>m.castle).length,2);c.board[sq('f8')]='bR';assert.ok(!C.legalChess(c,'w').some(m=>m.castle==='K'));c.board[sq('f8')]=null;const n=C.moveChess(c,C.legalChess(c,'w').find(m=>m.from===0&&m.to===8));assert.equal(n.rights.wQ,false)});
test('promotion offers all four choices and never keeps a pawn on rank eight',()=>{const c=chess({e1:'wK',h8:'bK',a7:'wP'});const moves=C.legalChess(c,'w').filter(m=>m.from===48);assert.deepEqual(moves.map(m=>m.promotion).sort(),['B','N','Q','R']);for(const m of moves)assert.equal(C.moveChess(c,m).board[56],'w'+m.promotion)});
test('en passant captures the passed pawn but cannot expose the king',()=>{let c=chess({e1:'wK',a8:'bK',e5:'wP',d7:'bP'});c=C.moveChess(c,C.legalChess(c,'b').find(m=>m.from===sq('d7')&&m.to===sq('d5')));const m=C.legalChess(c,'w').find(m=>m.epCapture!=null);assert.equal(m.to,sq('d6'));assert.equal(C.moveChess(c,m).board[sq('d5')],null);c.board[sq('e8')]='bR';assert.ok(!C.legalChess(c,'w').some(m=>m.epCapture!=null))});
test('kings are never captured and cannot move into each other',()=>{const c=chess({e1:'wK',e3:'bK'});assert.ok(!C.legalChess(c,'w').some(m=>m.to===sq('e2')))});
test('race setup has exactly 15 checkers each',()=>{const r=R.createRace();assert.equal(r.points.reduce((a,b)=>a+Math.max(b,0),0),15);assert.equal(r.points.reduce((a,b)=>a+Math.max(-b,0),0),15)});
test('race hit and priority re-entry preserve checker totals',()=>{const r=bareRace();r.points[8]=1;r.points[5]=-1;r.off={w:14,b:14};const n=R.moveRace(r,'w',R.raceMoves(r,'w',3)[0]);assert.equal(n.bar.b,1);assert.equal(n.points[5],1);assert.ok(R.raceMoves(n,'b',2).every(m=>m.from==='bar'));assert.equal(R.moveRace(n,'b',R.raceMoves(n,'b',2)[0]).bar.b,0)});
test('two checkers block an entry; allied stacks have no two-piece limit',()=>{const r=bareRace();r.bar.w=1;r.points[23]=-2;assert.equal(R.raceMoves(r,'w',1).length,0);r.points[23]=4;assert.equal(R.moveRace(r,'w',R.raceMoves(r,'w',1)[0]).points[23],5)});
test('bearing off is exact, home-only, with no checker on bar',()=>{const r=bareRace();r.points[1]=1;r.off.w=14;assert.equal(R.raceMoves(r,'w',3).length,0);assert.ok(R.raceMoves(r,'w',2).some(m=>m.to==='off'));r.bar.w=1;assert.ok(!R.raceMoves(r,'w',2).some(m=>m.to==='off'));r.bar.w=0;r.points[8]=1;assert.ok(!R.raceMoves(r,'w',2).some(m=>m.to==='off'))});
test('opening ties do not hang and the higher die starts',()=>{let g=G.createGame();g=G.roll(g,[4,4]);assert.equal(g.phase,'opening');g=G.roll(g,[2,5]);assert.equal(g.turn,'b');assert.equal(g.phase,'play');assert.deepEqual(g.dice,[2,5])});
test('doubles give four independently consumable dice',()=>{let g=G.createGame();g.phase='roll';g=G.roll(g,[3,3]);assert.equal(g.dice.length,4);const a=G.actions(g).find(a=>a.type==='race');g=G.play(g,a.id);assert.equal(g.used.filter(Boolean).length,1)});
test('chess costs are exact: knight 3, king 1, sliding distance or two-die sum',()=>{let g=playFixture();g.chess=chess({e1:'wK',e8:'bK',a1:'wR',b1:'wN'});const a=G.actions(g);assert.ok(a.some(m=>m.type==='chess'&&m.from===0&&m.to===24&&m.mask===3));assert.ok(!a.some(m=>m.type==='chess'&&m.from===0&&m.to===32));assert.ok(a.filter(m=>m.from===1&&m.type==='chess').every(m=>m.mask===3));assert.ok(a.filter(m=>m.from===4&&m.type==='chess').every(m=>m.mask===1))});
test('two-die payment consumes both values without mutating the source',()=>{const g=playFixture();g.chess=chess({e1:'wK',e8:'bK',a1:'wR'});const saved=JSON.stringify(g);const a=G.actions(g).find(m=>m.type==='chess'&&m.from===0&&m.to===24);const n=G.play(g,a.id);assert.equal(n.phase,'roll');assert.equal(n.turn,'b');assert.equal(JSON.stringify(g),saved);assert.throws(()=>G.play(n,a.id))});
test('royal rescue allows a legal check defense despite unusable dice',()=>{let g=playFixture();g.chess=chess({e1:'wK',e8:'bR',a8:'bK'});g.dice=[6,6,6,6];g.used=[false,false,false,false];const a=G.actions(g);assert.ok(a.length>0);assert.ok(a.every(a=>a.rescue&&a.type==='chess'));g=G.play(g,a[0].id);assert.equal(g.turn,'b');assert.equal(C.inCheck(g.chess,'w'),false)});
test('giving check ends the attacker turn; true mate wins immediately',()=>{let g=playFixture();g.chess=chess({a1:'wK',b1:'wR',h8:'bK'});g.dice=[6,1];g.used=[false,false];const a=G.actions(g).find(a=>a.type==='chess'&&a.from===sq('b1')&&a.to===sq('h1'));g=G.play(g,a.id);assert.equal(g.turn,'b');assert.equal(g.phase,'roll');g=playFixture();g.chess=chess({f6:'wK',g6:'wQ',h8:'bK'});const mate=G.actions(g).find(a=>a.type==='chess'&&a.from===sq('g6')&&a.to===sq('g7'));g=G.play(g,mate.id);assert.equal(g.winner,'w');assert.equal(g.reason,'mat')});
test('the fifteenth race exit wins immediately',()=>{let g=playFixture();g.race=bareRace();g.race.points[0]=1;g.race.off={w:14,b:15};const a=G.actions(g).find(a=>a.type==='race'&&a.to==='off');g=G.play(g,a.id);assert.equal(g.winner,'w');assert.equal(g.reason,'course')});
test('blocked race does not forbid chess; no legal action auto-passes',()=>{let g=playFixture();g.race.bar.w=15;g.race.points.fill(0);g.race.points[23]=-2;g.race.points[22]=-2;g.race.off.b=11;assert.ok(G.actions(g).some(a=>a.type==='chess'));g.phase='roll';g.chess=chess({a1:'wK',c2:'bK',b3:'bQ'});g=G.roll(g,[1,2]);assert.equal(g.turn,'b');assert.equal(g.phase,'roll')});
test('waiting dice are not discarded when another move could unlock them',()=>{let g=playFixture();g.race=bareRace();g.race.points[6]=1;g.race.points[5]=-2;g.race.off={w:14,b:13};g.chess=chess({a1:'wK',h8:'bK'});g.dice=[1,2];const move=G.actions(g).find(a=>a.type==='race'&&a.to===4);g=G.play(g,move.id);assert.equal(g.used[0],false);assert.ok(G.actions(g).some(a=>a.type==='race'&&a.to===3))});
test('invalid dice and fabricated/stale actions are rejected',()=>{assert.throws(()=>G.roll(G.createGame(),[0,7]));const g=playFixture();assert.throws(()=>G.play(g,'forged'));assert.equal(G.isState({}),false);assert.equal(G.isState(G.createGame()),true)});
test('all AI levels return an actual legal action',()=>{const g=G.roll(G.createGame(),[3,1]);for(const level of ['easy','medium','hard']){const id=A.choose(g,level,seeded(30));assert.ok(G.actions(g).some(a=>a.id===id))}});
test('400-turn limit is a documented draw, not a silent frozen game',()=>{let g=playFixture();g.ply=399;g.dice=[1];g.used=[false];g=G.play(g,G.actions(g).find(a=>a.type==='race').id);assert.equal(g.winner,'draw');assert.equal(g.reason,'limite')});
test('100 seeded complete games conserve pieces and always reach a result',()=>{let wins=0,draws=0,steps=0;for(let seed=1;seed<=100;seed++){const rand=seeded(seed);let g=G.createGame();let guard=0;while(!g.winner){assert.ok(++guard<=2100,'a game must terminate within the configured bound');if(g.phase!=='play'){g=G.roll(g,[1+Math.floor(rand()*6),1+Math.floor(rand()*6)]);}else{const a=G.actions(g);assert.ok(a.length>0,'UI must never wait for an impossible action');g=G.play(g,a[Math.floor(rand()*a.length)].id);}assert.ok(G.isState(g),'state invariants');steps++;}g.winner==='draw'?draws++:wins++;}console.log(JSON.stringify({seededGames:100,wins,draws,steps}));assert.equal(wins+draws,100)});

test('black checkers use the opposite entry and exact exit directions',()=>{const r=bareRace();r.bar.b=1;r.off.b=14;assert.equal(R.raceMoves(r,'b',6)[0].to,5);r.bar.b=0;r.points[22]=-1;assert.ok(R.raceMoves(r,'b',2).some(m=>m.to==='off'));assert.ok(!R.raceMoves(r,'b',3).some(m=>m.to==='off'))});
test('three repetitions are checked on the complete hybrid position',()=>{let g=playFixture();g.chess=chess({a1:'wK',h8:'bK'});for(let i=0;i<16&&!g.winner;i++){g.phase='play';g.dice=[1];g.used=[false];const [from,to]=[['a1','a2'],['h8','h7'],['a2','a1'],['h7','h8']][i%4];const a=G.actions(g).find(a=>a.type==='chess'&&a.from===sq(from)&&a.to===sq(to));assert.ok(a);g=G.play(g,a.id);}assert.equal(g.winner,'draw');assert.equal(g.reason,'répétition')});
test('a corrupted nonterminal save with an already completed race is rejected',()=>{const g=G.createGame();g.race.points=g.race.points.map(n=>Math.min(n,0));g.race.off.w=15;assert.equal(G.isState(g),false)});
for(const level of ['easy','medium','hard'])test(`${level} AI completes an entire deterministic game legally`,()=>{let g=G.createGame();const rand=seeded(901),start=Date.now();let steps=0;while(!g.winner){assert.ok(++steps<=2100);if(g.phase!=='play')g=G.roll(g,[1+Math.floor(rand()*6),1+Math.floor(rand()*6)]);else {const id=A.choose(g,level,rand);assert.ok(G.actions(g).some(a=>a.id===id));g=G.play(g,id);}assert.ok(G.isState(g));}console.log(JSON.stringify({AI:level,result:g.winner,reason:g.reason,steps,ms:Date.now()-start}));});
