import {createGame,rollActions,legalMoves,entryMoves,applyMove,bearOff,canBearOff} from './engine.js';import{chooseMove}from'./ai.js';
const glyph={white:{king:'♔',queen:'♕',rook:'♖',bishop:'♗',knight:'♘'},black:{king:'♚',queen:'♛',rook:'♜',bishop:'♝',knight:'♞'}};
let game=createGame(),selected=null,actionIndex=0;
const $=s=>document.querySelector(s),board=$('#board'),dice=$('#dice'),status=$('#status');
function currentDie(){return game.actions[actionIndex]}
function render(){
 board.innerHTML='';for(let y=7;y>=0;y--)for(let x=0;x<6;x++){const c=document.createElement('div');c.className='cell '+((x+y)%2?'dark':'light');c.dataset.x=x;c.dataset.y=y;const ps=game.pieces.filter(p=>!p.prison&&!p.off&&p.x===x&&p.y===y);ps.forEach((p,i)=>{const e=document.createElement('span');e.className='piece '+p.color;e.textContent=glyph[p.color][p.type];e.style.transform=`translate(${i?12:-4}px,${i?8:-3}px)`;e.onclick=ev=>{ev.stopPropagation();select(p.id)};c.append(e)});if(ps.length===2){const s=document.createElement('b');s.className='stack';s.textContent='BASTION';c.append(s)}c.onclick=()=>moveTo(x,y);board.append(c)}
 dice.innerHTML=game.actions.map((d,i)=>`<span class="die ${i<actionIndex?'used':''}">${d}</span>`).join('');
 for(const color of ['white','black']){const own=game.pieces.filter(p=>p.color===color);$('#'+color+'Stats').innerHTML=`Prison: <b>${own.filter(p=>p.prison).length}</b><br>Sorties: <b>${own.filter(p=>p.off).length}/6</b>`}
 status.textContent=game.winner?`Victoire des ${game.winner==='white'?'Blancs':'Noirs'} !`:game.actions.length?(`${game.turn==='white'?'Blancs':'Noirs'} — action ${Math.min(actionIndex+1,game.actions.length)}/${game.actions.length}`):(`${game.turn==='white'?'Blancs':'Noirs'} — lancez les dés`);
}
function select(id){if(game.winner||!game.actions.length)return;const p=game.pieces.find(q=>q.id===id);if(!p||p.color!==game.turn)return;selected=id;document.querySelectorAll('.cell').forEach(c=>c.classList.remove('target','capture'));let moves=p.prison?entryMoves(game,p.color,currentDie()):legalMoves(game,id,currentDie());moves.forEach(m=>{const c=[...document.querySelectorAll('.cell')].find(e=>+e.dataset.x===m.x&&+e.dataset.y===m.y);c?.classList.add(m.capture?'capture':'target')})}
function moveTo(x,y){if(!selected)return;const p=game.pieces.find(q=>q.id===selected),die=currentDie();const moves=p.prison?entryMoves(game,p.color,die):legalMoves(game,selected,die);if(!moves.some(m=>m.x===x&&m.y===y))return;game=applyMove(game,selected,{x,y},die);selected=null;nextAction()}
function nextAction(){actionIndex++;render();if(actionIndex>=game.actions.length){game.turn=game.turn==='white'?'black':'white';game.actions=[];actionIndex=0;render();setTimeout(aiTurn,400)}}
$('#roll').onclick=()=>{if(game.actions.length||game.winner)return;game.actions=rollActions([1+Math.floor(Math.random()*6),1+Math.floor(Math.random()*6)]);actionIndex=0;render();if($('#mode').value==='ai'&&game.turn==='black')setTimeout(aiTurn,400)};
function aiTurn(){if($('#mode').value!=='ai'||game.turn!=='black'||game.winner)return;if(!game.actions.length){game.actions=rollActions([1+Math.floor(Math.random()*6),1+Math.floor(Math.random()*6)]);actionIndex=0;render()}const die=currentDie(),a=chooseMove(game,die,$('#level').value);if(a)game=a.bearOff?bearOff(game,a.pieceId,die):applyMove(game,a.pieceId,a.to,die);nextAction()}
$('#new').onclick=()=>{game=createGame();selected=null;actionIndex=0;render()};$('#mode').onchange=e=>{$('#levelWrap').style.display=e.target.value==='ai'?'grid':'none';game=createGame();actionIndex=0;render()};$('#rules').onclick=()=>$('#help').showModal();$('#close').onclick=()=>$('#help').close();
render();